services:

  authservice:
    container_name: authservice
    build:
      context: ./Auth
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: auth@123
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge