@host = http://localhost:5001


### Register
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "email": "user2@example.com",
  "password": "YourPassword123!",
  "username": "yourusername2"
}

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "YourPassword123!"
}

### Refresh Token
POST {{host}}/api/auth/refresh-token