services:

  orderservice:
    container_name: orderservice
    build:
      context: ./Orders.Api
      dockerfile: Dockerfile
    depends_on:
      ordersdb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__postgresdb=Host=ordersdb;Database=ordersdb;Username=postgres;Password=order@123
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672/
      - Jwt__Issuer=http://orderservice
      - Jwt__Audience=api-clients
      - Jwt__Key=12382198398#*@&*$*#$&#*$#$AKSJDLKSADDAKDOPADI&^&^%$#@!@#$
      - USE_E2E_STUBS=true
    ports:
      - "5002:8080"
    networks:
      - backend

  ordersdb:
    container_name: ordersdb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: order@123
      POSTGRES_DB: ordersdb
    ports:
      - "5433:5432"
    volumes:
      - orders-pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


volumes:
  orders-pgdata:
  rabbitmq-data:

networks:
  backend:
    driver: bridge