include:
  - path: ./auth/docker-compose.auth.yml
  - path: ./api-gateway/docker-compose.gateway.yml
  - path: ./orders/docker-compose.orders.yml

services:
  # Other services will be included from their respective docker-compose files
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data: