services:

  orderservice:
    container_name: orderservice
    build:
      context: ./Order.Api
      dockerfile: Dockerfile
    depends_on:
      orderdb:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__postgresdb=Host=orderdb;Database=orderdb;Username=postgres;Password=order@123
      - Jwt__Issuer=http://orderservice
      - Jwt__Audience=api-clients
      - Jwt__Key=12382198398#*@&*$*#$&#*$#$AKSJDLKSADDAKDOPADI&^&^%$#@!@#$
    ports:
      - "5002:8080"
    networks:
      - backend

  orderdb:
    container_name: orderdb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: order@123
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  pgdata:

networks:
  backend:
    driver: bridge