services:

  shoppingcartservice:
    container_name: shoppingcartservice
    build:
      context: ./ShoppingCart.Api
      dockerfile: Dockerfile
    depends_on:
      shoppingcartdb:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__postgresdb=Host=shoppingcartdb;Database=shoppingcartdb;Username=postgres;Password=shoppingcart@123
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672/
      - Jwt__Issuer=http://shoppingcartservice
      - Jwt__Audience=api-clients
      - Jwt__Key=12382198398#*@&*$*#$&#*$#$AKSJDLKSADDAKDOPADI&^&^%$#@!@#$
    ports:
      - "5003:8080"
    networks:
      - backend

  shoppingcartdb:
    container_name: shoppingcartdb
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shoppingcart@123
      POSTGRES_DB: shoppingcartdb
    ports:
      - "5434:5432"
    volumes:
      - shoppingcart-pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  shoppingcart-pgdata:
  rabbitmq-data:

networks:
  backend:
    driver: bridge